### ISSUE TITLE
Allow registering and logging in

### ISSUE THREAD

**Issue by stevegrossi** [stevegrossi/sengoku#56]
Currently, every time you join a game you have to enter your name. It would be nice to let folks log in (perhaps using [phoenix_gen_auth](https://github.com/aaronrenner/phx_gen_auth)) with a username that's used automatically whenever they join.

Eventually, this might pave the way to:

- let registered users choose a preferred color they get dibs on
- keep track of wins/losses on a profile page
- achievements! 🏆

**Comment by yakryder** [comment]
Fixed by #74

**Comment by stevegrossi** [comment]
Thanks for following up and closing this one! ❤️
