### ISSUE TITLE
Game allows single unit attacks and abandoned territories

### ISSUE THREAD

**Issue by yakryder** [stevegrossi/sengoku#6]
![image](https://user-images.githubusercontent.com/14241275/31057508-e3d40452-a6b1-11e7-94cd-e2f5bbfc545f.png)

1) Begin a hot seat game
2a) During a turn, attack an adjacent enemy territory with one unit.
OR
2b) Move all units from one friendly territory to another.

Expected(I): Attacker cannot attack with one unit.
Actual(I): Attacker can attack with one unit. Whether victorious or defeated, friendly territory from which the attack was staged will now be abandoned. 

Expected(II): Moving player cannot abandon a friendly territory.
Actual(II): Moving player can move all occupying units from one friendly territory to another.

**Comment by stevegrossi** [comment]
This feels related to #7, let's discuss it there!
