### ISSUE TITLE
Abandoned territories still count as controlled

### ISSUE THREAD

**Issue by yakryder** [stevegrossi/sengoku#7]
![image](https://user-images.githubusercontent.com/14241275/31057750-c531c2ba-a6b5-11e7-8023-07f7a69efb83.png)

Related to #6 

Steps to reproduce:
1) Start a hot seat game.
2) Select a player you want to win the game.
3) Create one or more abandoned territory not owned by your selected winner. (See #6)
4) Take over all other territories on the map.

Expected(I): When a player no longer has units on the map, they cease to accrue units.
Actual(I): When a player no longer has units on the map, they continue to accrue units as long as they have at least one abandoned territory still controlled by them.

Expected(II): The game ends when only one player still has units on the map.
Actual(II): The game continues as these abandoned-but-still-owned territories are technically still owned by the other player(s).

**Comment by stevegrossi** [comment]
Thanks for bringing this up! This was something I had a hard time making my mind up about. I know Risk requires that every territory to be held by at least one army, and when attacking you must leave at least one army behind. But there's another game I've been modeling Sengoku off of—[Compact Conflict](http://js13kgames.com/entries/compact-conflict), tons of fun!—that lets you move all of your forces out of a territory while still maintaining control.

I went with this approach for (maybe?) these reasons:

- Slightly simpler logic (I'm lazy!) just letting you move any units around you want, without enforcing that one is always left behind when attacking/moving.
- I can imagine this matching reality. If Ryder's army controls a region but moves all its military forces away to the front line, the people in the region would probably still say "Ryder's in charge" until someone else comes and takes control.
- The board looks a little cleaner with fewer numbers on it

I'll admit that none of these reasons is particularly compelling, so if there's a case to be made for requiring every tile be held by at least one unit—especially if it makes the game more fun, fair, or interesting—I'm all for it.

**Comment by yakryder** [comment]
So it seems like every bug I've opened is FAD. The reason they seem like bugs is the divergence from the Risk paradigm when the game is touted as a Risk-like. To my understanding the README either doesn't explain or doesn't sufficiently highlight the differences.

These might all be documentation/UX bugs

**Comment by yakryder** [comment]
Although allowing unoccupied territories does let you blitz across an already small map and might give the first player an unreasonably unfair advantage. I think play-testing with a broader audience would help

**Comment by stevegrossi** [comment]
> To my understanding the README either doesn't explain or doesn't sufficiently highlight the differences.
> 
> These might all be documentation/UX bugs

👍  I'll at least improve the docs around these, but am definitely interested in feedback on whether the way these features are designed could be improved.

> allowing unoccupied territories does let you blitz across an already small map

A great point. At least with a minimum of one-unit-per-territory it means attackers have *some* resistance. I do think reducing the possibility of far-reaching blitzes may make the game more fun. That's one of the more unrealistic details about Risk: typically the larger an army is, the more slowly it moves, but in Risk you can march an enormous army across the world in a single turn if the territories you're marching through are poorly defended. Though I suppose the tradeoff is that you'd end up spreading your forces out pretty thin...

An alternative I considered was a rule that players can only attack from tiles they owned at the start of their turn. This would mean if you capture a tile during your turn, you can't keep rolling on through. This feels most realistic to me, though I don't really know the effect it would have on gameplay. I'd love to do some play-testing—it's mostly been just me playing against myself so far 😉

**Comment by stevegrossi** [comment]
To be clear, I am interested in making this change (preventing you from abandoning tiles) and playtesting the impact, so I want to keep this issue open.

**Comment by stevegrossi** [comment]
This was the right call—thanks @SherSpock!
